apiVersion: tmc.tanzufield.vmware.com/v1
kind: TMCNamespace
metadata:
  name: testing-controller
  labels:
    version: v1
spec:
  fullName:
    clusterName: gke-2
    managementClusterName: attached
    name: testing-controller
    provisionerName: attached
  meta:
    labels:
      tenant: group-0001
  spec:
    workspaceName: group-0001
