apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: sa-per-ns
spec:
  resources:
  - apiVersion: v1
    resource: namespaces
    labelSelector:
      matchExpressions:
      - {key: custom-sa , operator: Exists}
  attachments:
  - apiVersion: v1
    resource: serviceaccounts
  hooks:
    sync:
      webhook:
        url: http://sa-per-ns.metacontroller/sync
    finalize:
      webhook:
        url: http://sa-per-ns.metacontroller/finalize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-per-ns
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-per-ns
  template:
    metadata:
      labels:
        app: sa-per-ns
    spec:
      containers:
      - name: hooks
        image: metacontroller/jsonnetd:0.1
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: sa-per-ns-hooks
---
apiVersion: v1
kind: Service
metadata:
  name: sa-per-ns
  namespace: metacontroller
spec:
  selector:
    app: sa-per-ns
  ports:
  - port: 80
    targetPort: 8080