---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tmcnamespaces.tmc.tanzufield.vmware.com
spec:
  group: tmc.tanzufield.vmware.com
  scope: Namespaced
  names:
    plural: tmcnamespaces
    singular: tmcnamespace
    kind: TMCNamespace
    shortNames: ["tmcns"]
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TMC Namespace
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              fullName:
                description: object that holds all of the name details for the namesapce
                type: object
                properties:
                  cluster_name:
                    description: cluster name
                    type: string
                  managementClusterName:
                    description: management cluster name
                    type: string
                  name:
                    description: name of the namespace
                    type: string
                  provisionerName:
                    description: provisioner name
                    type: string
              meta:
                type: object
                properties:
                  labels:
                    type: object
                    additionalProperties:
                      type: string
              spec:
                properties:
                  workspaceName:
                    description: workspace name
                    type: string
            required:
            - fullName
            - spec.workspaceName
            type: object
          status:
            properties:
              phase:
                type: string
              conditions:
                type: object
                properties:
                  Ready:
                    type: object
                    properties:
                      status:
                        type: string
                      reason: 
                        type: string
                      type:
                        type: string
                      lastTransitionTime:
                        type: string
              observedGeneration:
                type: integer
            type: object
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}