---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: tmc-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: tmc.tanzufield.vmware.com/v1
    resource: tmcnamespaces
    labelSelector:
      matchLabels:
        version: v1
  resyncPeriodSeconds: 120
  hooks:
    sync:
      webhook:
        url: http://tmc-controller.metacontroller/sync
        timeout: 30s
    finalize:
      webhook:
        url: http://tmc-controller.metacontroller/finalize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmc-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmc-controller
  template:
    metadata:
      labels:
        app: tmc-controller
    spec:
      containers:
      - name: controller
        image: python:3.9
        command: ["/bin/sh","-c"]
        args: ["pip install requests; python /hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        env:
        - name: TMC_HOST
          valueFrom:
            secretKeyRef:
              name: tmcinfo
              key: TMC_HOST
        - name: CSP_TOKEN
          valueFrom:
            secretKeyRef:
              name: tmcinfo
              key: CSP_TOKEN
        - name: DRY_RUN
          valueFrom:
            secretKeyRef:
              name: tmcinfo
              key: DRY_RUN
              optional: true
      volumes:
      - name: hooks
        configMap:
          name: tmc-controller
---
apiVersion: v1
kind: Service
metadata:
  name: tmc-controller
  namespace: metacontroller
spec:
  selector:
    app: tmc-controller
  ports:
  - port: 80
